### ISSUE TITLE
"Little Endian" and "Big Endian" swapped in README.md

### ISSUE THREAD

**Issue by polettix** [p6-pdf/Native-Packing-p6#4]
Hi! The current formulation in README.md is:

> The two fixed modes are:
> * Vax (big endian) - least significant byte written first
> * Network (little endian) - most significant byte written first

The "big endian" and "little endian" strings are swapped, it should be:

> The two fixed modes are:
> * Vax (little endian) - least significant byte written first
> * Network (big endian) - most significant byte written first

**Comment by dwarring** [comment]
Thanks. Fixed in Native::Packing release 0.0.6.
